blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
	path(r'',views.IndexView.as_view(),name='index'),# 以空字符串开头且以空字符串结尾
	path(r'<int:pk>/detail/',views.PostDetailView.as_view(),name='detail'),
	path(r'archives/<int:year>/<int:month>/', views.ArchivesView.as_view(), name='archives'),
	path(r'category/<int:pk>/',views.CategoryView.as_view(),name='category'),
	path(r'tag/<int:pk>/',views.TagView.as_view(),name='tag'),
	path(r'FERImage/',views.FERImage,name='FERImage'),
	path(r'FERWebcam/',views.FERWebcam,name='FERWebcam'),
	path(r'FERIntroduction/',views.FERIntroduction,name='FERIntroduction'),
	]

blogproject/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'',include('blog.urls')),
    path(r'',include('comments.urls')),
]

comments/urls.py
from django.urls import path
from . import views

app_name = 'comments'
urlpatterns = [
	path(r'comment/post/<int:post_pk>/',views.post_comment,name='post_comment'),
	]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible

import markdown
from django.utils.html import strip_tags

# Create your models here.
class Category(models.Model):
	'''
	CharField 指定了分类名 name 的数据类型，CharField 是字符
	max_length =100规定长度
	'''
	name = models.CharField(max_length=100)
	def __str__(self):
		return self.name


class Tag(models.Model):
	'''
	标签类
	'''
	name = models.CharField(max_length=100)
	def __str__(self):
		return self.name

class Post(models.Model):
	'''
	文章数据库
	'''
	# 文章标题
	title = models.CharField(max_length=70)

	# 文章正文
	body = models.TextField()

	# 创建时间 和 最后一次修改时间
	create_time = models.DateTimeField()
	modified_time = models.DateTimeField()


	# 文章摘要，balnk允许空值
	excerpt = models.CharField(max_length=200,blank=True)

	## 分类数据库 和 标签数据库的 关联
	# ForeignKey一对多的关系
	# ManyToManyField 多对多的关系
	category = models.ForeignKey(Category,on_delete=models.CASCADE)
	tags = models.ManyToManyField(Tag,blank=True)


	# 文章作者
	author = models.ForeignKey(User,on_delete=models.CASCADE)

	# 阅读量
	views = models.PositiveIntegerField(default = 0) # 初始值为0

	# 摘要
	body = models.TextField()
	excerpt = models.CharField(max_length=200,blank=True)

	def increase_views(self):
		self.views += 1
		self.save(update_fields=['views'])

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("blog:detail", kwargs={"pk": self.pk})

	# 自动摘要
	def save(self,*args,**kwargs):
		# 如果没填摘要
		if not self.excerpt:
			# 先实例化一个Markdown类，用于渲染body
			md = markdown.Markdown(extensions=[
				 'markdown.extensions.extra',
				 'markdown.extensions.codehilite',
			])
			# 先将Markdown文本渲染成HTML 文本
			# strip_tags 去掉HTML文本的全部HTML标签
			# 从文本中摘取前 54 个字符给 excerpt 
			self.excerpt = strip_tags(md.convert(self.body))[:54]
		
		# 调用父类的 SAVE 方法 保存数据
		super(Post,self).save(*args,**kwargs)


	class Meta:
		ordering = ['create_time']
	

comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible
# Create your models here.

@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    
    post = models.ForeignKey('blog.Post',on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]
    

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Post,Category,Tag
from comments.forms import CommentForm
import markdown

from django.views.generic import ListView, DetailView
# Create your views here.
'''
需要 pip install markdown
	 pip install Pygments

'''

def index(request):
	post_list = Post.objects.all().order_by('-create_time')
	return render(request,'blog/index.html',context={'post_list':post_list})

def detail(request,pk):
	post = get_object_or_404(Post,pk=pk)

	# 阅读量 +1
	post.increase_views()

	#markdown格式
	post.body = markdown.markdown(post.body,extensions=[
		'markdown.extensions.extra',
		'markdown.extensions.codehilite', #语法高亮拓展
		'markdown.extensions.toc', #自动生成目录
	])

	form = CommentForm()\
	#获取这篇Post下所有评论
	comment_list = post.comment_set.all()
	#模板变量
	context = {
		'post':post,
		'form':form,
		'comment_list':comment_list
	}

	return render(request, 'blog/detail.html',context={'post':post})

def archives(request, year, month):
    post_list = Post.objects.filter(create_time__year=year,
                                    create_time__month=month
                                    ).order_by('-create_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})

def category(request,pk):
	cate = get_object_or_404(Category,pk=pk)
	post_list = Post.objects.filter(category=cate).order_by('-create_time')
	return render(request,'blog/index.html',context={'post_list':post_list})

def FERImage(request):
	return render(request,'FER/src/facial_expression_image.html')
def FERWebcam(request):
	return render(request,'FER/src/facial_expression_vedio.html')
def FERIntroduction(request):
	return render(request,'FER/src/Introduction.html')



class IndexView(ListView):
	model = Post
	template_name = 'blog/index.html'
	context_object_name = 'post_list'
	## 指定 paginate_by 开启分页功能
	paginate_by = 10

	## 重写get_queryset 对post_list排序
	def get_queryset(self):
		return super(IndexView,self).get_queryset().order_by('-create_time')

	def get_context_data(self,**kwargs):
		"""
		在视图函数中将模板变量通过render传递
		"""

		# 获得父类生成的传递给模板的字典
		context = super().get_context_data(**kwargs)

		# 父类已经有paginator_、age_obj、is_paginated三个模板变量，
		# paginator 是Paginator的一个实例
		# page_obj 是Page 的一个实例，
		# is-paginated 是一个bool变量，用于指示是否分页
		paginator = context.get('paginator')
		page = context.get('page_obj')
		is_paginated = context.get('is_paginated')

		# 调用自己写的pagination_data方法获得分页导航条需要的数据
		pagination_data = self.pagination_data(paginator,page,is_paginated)

		# 将分页导航页的模板变量更新到context中，注意pagination_data 方法返回的也是一个字典
		context.update(pagination_data)

		# 将更新后的context返回，以便ListView 使用这个变量
		# 注意此时context字典中已经有了显示分页导航条所需的数据
		return context

	def pagination_data(self,paginator,page,is_paginated):
		if not is_paginated:
			# 如果没有分页就返回空
			return {}

		#  左边连续的页码号，初始值为空
		left = []

		# 右边连续的页码号，初始值为空
		right = []

		#标记第一页是否需要显示省略号
		left_has_more = False

		# 标识最后一页页码是否需要显示省略号
		right_has_more = False

		
		#第一个标签是否显示，初始为 False
		first = False

		#最后一个标签是否需要显示，初始为 False
		last = False

		# 获得用户当前请求的页码号
		page_number = page.number

		# 获得分页后的总数
		total_pages = paginator.num_pages

		# 获得整个分页页码列表
		page_range = paginator.page_range

		if page_number == 1:
			# 如果请求的是第一页的数据，那么left = []
			# 只需要右边的连续页码号
			right = page_range[page_number:page_number + 2]

			# 如果最右边的页码号比最后一页的页码号减去1还要小，
			# 说明最右边的页码号和最后一页的页码号之间还有其他页码
			if right[-1] < total_pages - 1:
				right_has_more = True

			# 判断是否需要显示最后一页的标签
			if right[-1] < total_pages:
				last = True
			
		elif page_number == total_pages:
			# 如果请求的是最后一页的数据，那么右边就不需要,right = []
			# 只要获取当其页码左边的页码号
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

			# 如果最左边的页码比第二页大
			# 说明 1~最左边页码之间需要省略号
			if left[0] > 2:
				left_has_more = True
			
			# 如果最左边的页码比第一页的大，说明需要显示第一页
			if left[0] > 1:
				first = True
			
		else:
			# 如果请求的既不是第一页也不是最后一页，获取左右两边连续页码
			# 获取当前页码左右两个连续页码
			left = page_range[(page_number - 3) if(page_number - 3)>0 else 0:page_number -1]
			right = page_range[page_number:page_number + 2] 

			# 是否需要显示最后一页和最后一页前的省略号
			if right[-1] < total_pages - 1:
				right_has_more = True
			if right[-1] < total_pages:
				last = True

			# 是否需要显示第一页和第一页后的省略号
			if left[0] > 2:
				left_has_more = True
			if left[0] > 1:
				first = True
			
		data = {
			'left':left,
			'right':right,
			'left_has_more':left_has_more,
			'right_has_more':right_has_more,
			'first':first,
			'last':last,
		}

		return data
			
class CategoryView(ListView):
	model = Post
	template_name = 'blog/index.html'
	context_object_name = 'post_list'

	def get_queryset(self):
		cate = get_object_or_404(Category,pk=self.kwargs.get('pk'))
		return super(CategoryView,self).get_queryset().filter(category=cate).order_by('-create_time')


class ArchivesView(ListView):
	model = Post
	template_name = 'blog/index.html'
	context_object_name = 'post_list'

	def get_queryset(self):
		year = self.kwargs.get('year')
		month = self.kwargs.get('month')
		return super(ArchivesView,self).get_queryset().filter(create_time__year=year,
                                    create_time__month=month
                                    ).order_by('-create_time')
	

class PostDetailView(DetailView):
	model = Post
	template_name = 'blog/detail.html'
	context_object_name = 'post'

	def get(self,request,*args,**kwargs):
		response = super(PostDetailView,self).get(request,*args,**kwargs)

		# 阅读量+1
		self.object.increase_views()
		return response

	def get_object(self,queryset=None):
		post = super(PostDetailView,self).get_object(queryset=None)
		post.body = markdown.markdown(post.body,
                                      extensions=[
                                          'markdown.extensions.extra',
                                          'markdown.extensions.codehilite',
                                          'markdown.extensions.toc',
                                      ])

		return post

	def get_context_data(self,**kwargs):
		context = super(PostDetailView,self).get_context_data(**kwargs)
		form = CommentForm()
		comment_list = self.object.comment_set.all()
		context.update({
			'form':form,
			'comment_list':comment_list
		})
		return context


class TagView(ListView):
	model = Post
	template_name = 'blog/index.html'
	context_object_name = 'post_list'

	def get_queryset(self):
		tag = get_object_or_404(Tag,pk=self.kwargs.get('pk'))
		return super(TagView,self).get_queryset().filter(tags=tag)

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
    <article class="post post-{{ post.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">{{ post.title }}</h1>
        <div class="entry-meta">
        <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
        <span class="post-date"><a href="#"><time class="entry-date"
                                                    datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
        <span class="post-author"><a href="#">{{ post.author }}</a></span>
        <span class="comments-link"><a href="#">4 评论</a></span>
        <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        {{ post.body|safe }}
            <div class="widget-tag-cloud">
                <ul>
                    标签：
                    {% for tag in post.tags.all %}
                        <li><a href="{% url 'blog:tag' tag.pk %}"># {{ tag.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
    </div>
    </article>
    <section class="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">URL：</label>
                    {{ form.url }}
                    {{ form.url.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论：</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>4</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <time class="submit-date"
                              datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
                        <div class="text">
                            {{ comment.text }}
                        </div>
                    </li>
                {% empty %}
                    暂无评论
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock main %}
{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        <ul>
            <li>
                <a href="#">教程特点</a>
            </li>
            <li>
                <a href="#">谁适合这个教程</a>
            </li>
            <li>
                <a href="#">在线预览</a>
            </li>
            <li>
                <a href="#">资源列表</a>
            </li>
            <li>
                <a href="#">获取帮助</a>
            </li>
        </ul>
    </div>
{% endblock toc %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                                datetime="{{ post.create_time }}">{{ post.create_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="#">{{ post.comment_set.count }}</a></span>
                    <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}
                </p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！ </div>

    {% endfor %}  
    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
    <div class="pagination">
        {% if is_paginated %}
        <div class="pagination">
        {% if first %}
            <a href="?page=1">1</a>
        {% endif %}
        {% if left %}
            {% if left_has_more %}
                <span>...</span>
            {% endif %}
            {% for i in left %}
                <a href="?page={{ i }}">{{ i }}</a>
            {% endfor %}
        {% endif %}
        <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
        {% if right %}
            {% for i in right %}
                <a href="?page={{ i }}">{{ i }}</a>
            {% endfor %}
            {% if right_has_more %}
                <span>...</span>
            {% endif %}
        {% endif %}
        {% if last %}
            <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
        {% endif %}
        </div>
        {% endif %}
    </div>
{% endblock main %}